### ISSUE TITLE
Backend checklist

### ISSUE THREAD

**Issue by EthanLuisMcDonough** [sweng421/final-project#1]
- [X] Setup WebSocket server
- [X] Implement basic authentication flow (sign in → pick username → send messages)
  - [X] Add error and confirmation replies after processing a state change 
- [X] Implement heartbeat
- [X] Implement username checking, storage, and cleanup
- [x] Add SSL encryption
- [x] Use hashing for password
- [x] Add endpoint exposing connection parameters
- [x] Load configuration properties from env
