### ISSUE TITLE
Plugin checklist

### ISSUE THREAD

**Issue by EthanLuisMcDonough** [sweng421/final-project#2]
- [x] Define plugin interface
- [x] Load in plugins on demand
- [x] Find way to leverage [LLAMA LLM](https://ai.meta.com/llama/) within plugin and implement logic

**Comment by EthanLuisMcDonough** [comment]
Removed [Anonymouth](https://github.com/psal/anonymouth) checkbox. Anonymouth/JStylo is very much an abandoned project and is hard to get running. LLAMA with GPU acceleration will be enough for the purposes of this project.
