### ISSUE TITLE
Connection checklist

### ISSUE THREAD

**Issue by EthanLuisMcDonough** [sweng421/final-project#3]
- [x] Use builder pattern to connect to server
  - [x] Send HTTP GET request to server to collect server details
     - Details include max message length, the chatroom websocket path, and whether the server is password protected
  - [x] Connect to websocket
  - [x] If a password is required, send password via websocket and check for error
  - [x] Send username via websocket and check for error
