### ISSUE TITLE
GUI Checklist

### ISSUE THREAD

**Issue by EthanLuisMcDonough** [sweng421/final-project#4]
- [x] Build connection screen
  - [x] Accepts server domain, username, and password
  - [x] Display error on failed connection
  - [x] Transition to chatroom on success
- [x] Build chatroom screen
  - [x] Scrolling message view
  - [x] Message field + send button
  - [x] Unanonymized message field + anonymize button
    - [x] Only enabled if a plugin has been loaded
  - [x] Subscription checkbox that notifies users when they're @'ed. Plays sound if enabled. Does nothing if left unchecked. Must use observer pattern.
  - [x] Plugin load button
    - [x] Display error of plugin failed to load
  - [x] Sign out button
    - [x] Redirects to connect screen
  - [x] Filter messages button
    - [x] Opens up dialog box prompting for user input and filter type
    - [x] Clicking search will display a list of cached messages that confirm to the given filter inside the dialog window
